global.globalStyle ={
    firstColor:'#FFBF3F',
    darkFirstColor:'#e0a739',
    Text48Bold:{fontSize:48 *unitHeight, color:'#333',fontWeight: 'bold'},
    Text32Bold:{fontSize:32 *unitHeight, color:'#333',fontWeight: 'bold'},
    Text28Bold:{fontSize:28 *unitHeight, color:'#333',fontWeight: 'bold'},
    Text30Bold:{fontSize:30 *unitHeight, color:'#333',fontWeight: 'bold'},
    Text30Normal:{fontSize:30 *unitHeight, color:'#333'},
    full:{width:'100%',height:'100%'},
    Text28Normal:{fontSize:28 *unitHeight, color:'#333'},
    Text26Normal:{fontSize:26 *unitHeight, color:'#333'},
    Text26Bold:{fontSize:26 *unitHeight, color:'#333',fontWeight:'bold'},
    Text26C25Normal:{fontSize:26 *unitHeight, color:'#252525'},
    Text24Normal:{fontSize:24 *unitHeight, color:'#333'},
    Text23Normal:{fontSize:23 *unitHeight, color:'#333'},
    Text24Bold:{fontSize:24 *unitHeight, color:'#333',fontWeight:'bold'},
    Text24C91Normal:{fontSize:24 *unitHeight, color:'#919191'},
    Text24CBFNormal:{fontSize:24 *unitHeight, color:'#BFBFBF'},
    Text20Normal:{fontSize:20 *unitHeight, color:'#666'},
    Text20Bold:{fontSize:20 *unitHeight, color:'#666',fontWeight:'bold'},
    pad20H86:{paddingLeft:20 *unitHeight, paddingRight:20 *unitHeight, height:86 *unitHeight, flexDirection:'row',alignItems:'center',},
    pad20H60:{paddingLeft:20 *unitHeight, paddingRight:20 *unitHeight, height:60 *unitHeight, flexDirection:'row',alignItems:'center',},
    pad20:{paddingLeft:20 *unitHeight, paddingRight:20 *unitHeight, flexDirection:'row',alignItems:'center',},
    pad20All:{padding:20 *unitHeight, flexDirection:'row',alignItems:'center',},
    mar20:{marginLeft:20 *unitHeight, marginRight:20 *unitHeight, flexDirection:'row',alignItems:'center',},
    partingLine12:{height: unitHeight *12, backgroundColor:'#F5F5F5',width:'100%'},
    partingLine2:{height: unitHeight *2, backgroundColor:'#F5F5F5',width:'100%'},
    partingLine1:{height: unitHeight *1, backgroundColor:'#F5F5F5',width:'100%'},
    partingLine1Col:{height: '60%', backgroundColor:'#F5F5F5',width:1 *unitHeight},
    partingLine2Col:{height: '60%', backgroundColor:'#F5F5F5',width:2 *unitHeight},
    button:{height:76 *unitHeight,marginLeft: 20 *unitHeight,marginRight: 20 *unitHeight,justifyContent:'center',alignItems:'center',marginTop:20 *unitHeight,marginBottom:20 *unitHeight,
        borderRadius:15 *unitHeight},
    radioUnselect:{width:28 *unitHeight,height:28*unitHeight,borderWidth:2 *unitHeight,borderColor:'#D2D2D2',borderRadius:15,opacity:1,padding:2 *unitHeight},
    radioSel:{width:'100%',height:'100%',borderRadius:15,backgroundColor:'#D6AE68'},
    confirmButton:{width:120 *unitHeight, },
    flexCfff:{flex: 1, backgroundColor: '#fff'},
    bigButtonEnable:{marginLeft:20 *unitHeight,marginRight:20 *unitHeight,height:86 *unitHeight,justifyContent: 'center',alignItems:'center',borderRadius:43 *unitHeight},
    bigButtonDisable:{marginLeft:20 *unitHeight,marginRight:20 *unitHeight,height:86 *unitHeight,justifyContent: 'center',alignItems:'center',backgroundColor:'#eee'},
};
